### PR TITLE
image_options: add new os fedora-cgroupv2

### PR DESCRIPTION
**Pull request by giuseppe**
add a new operating system "fedora-cgroupv2" to target Fedora running
with the cgroup v2 unified hierarchy.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by dobbymoodge** [comment]
Actually, if you could add a commit to fix the formatting errors pointed out in this test: https://travis-ci.com/openshift/origin-ci-tool/builds/147923802 that would be great. I know it's unrelated to this change, but it'll make the test pass :grin:

**Comment by giuseppe** [comment]
> Actually, if you could add a commit to fix the formatting errors pointed out in this test: https://travis-ci.com/openshift/origin-ci-tool/builds/147923802 that would be great. I know it's unrelated to this change, but it'll make the test pass grin

done, and tests are happy now

**Comment by giuseppe** [comment]
still not merged :/

**Pull request merged**
