### PR TITLE
add jenkins plugins to oct

### PR DESCRIPTION
**Pull request by gabemontero**
@stevekuznetsov @bparees ptal

### CODE REVIEW

**Comment by gabemontero** [comment]
updated the playbook - thanks

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
thanks @stevekuznetsov 

quick question:  to start seeing the new version of `oct` available for aos-cd-jobs, should I look for an update in https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_rhel_base/ or https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_rhel_build/  ?

**Comment by stevekuznetsov** [comment]
@gabemontero installation of this tool into the Jenkins master is described [here](https://github.com/openshift/ci-config/blob/master/doc/origin-ci.md#installation-onto-the-jenkins-master) -- once it's installed, you should run [`ami_build_origin_int_rhel_base`](https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_rhel_base/) for a new AMI

**Comment by gabemontero** [comment]
OK thanks for the pointers.  Looks like the install job noted in your first link completed successfully.  I've initiated https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_rhel_base/162/console for the second part (and that of course answers my original questions on what AMI update is needed).

**Pull request merged**
