### PR TITLE
Use lineinfile instead

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
```
$ cat /etc/sysconfig/docker-storage-setup 
# Edit this file to override any configuration options specified in
# /usr/lib/docker-storage-setup/docker-storage-setup.
#
# For more details refer to "man docker-storage-setup"
VG=docker

$ sudo vgs
  VG     #PV #LV #SN Attr   VSize  VFree 
  docker   1   1   0 wz--n- 25.00g 17.50g

$ sudo docker-storage-setup
INFO: Volume group backing root filesystem could not be determined
  Using default stripesize 64.00 KiB.
  Rounding up size to full physical extent 28.00 MiB
  Logical volume "docker-pool" created.
  Logical volume docker/docker-pool changed.

$ sudo vgs
  VG     #PV #LV #SN Attr   VSize  VFree 
  docker   1   2   0 wz--n- 25.00g 10.50g

$ sudo lvs
  LV                    VG     Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  docker-pool           docker twi-a-t--- 6.95g             0.00   0.13                            
  openshift-xfs-vol-dir docker -wi-ao---- 7.50g                                                    
```

Seems to work but does not have the data/metadata split as before -- I want to make sure that we are making as small of a diff from the previous setup to the new setup so we don't see regressions from that.

**Comment by sdodson** [comment]
`lvs -a` will display the subvolumes

**Comment by sdodson** [comment]
LGTM
```
# cat /etc/sysconfig/docker-storage
DOCKER_STORAGE_OPTIONS="--storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/docker-docker--pool --storage-opt dm.use_deferred_removal=true "

# lvs -a
  LV                    VG     Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  docker-pool           docker twi-a-t---  6.95g             0.00   0.13                            
  [docker-pool_tdata]   docker Twi-ao----  6.95g                                                    
  [docker-pool_tmeta]   docker ewi-ao---- 28.00m                                                    
  [lvol0_pmspare]       docker ewi------- 28.00m                                                    
  openshift-xfs-vol-dir docker -wi-ao----  7.50g                                                    
```

**Comment by stevekuznetsov** [comment]
Building https://ci.openshift.redhat.com/jenkins/view/AMI%20Publication%20Jobs/job/rhel_base_ami/13/

**Pull request merged**
