### PR TITLE
Turn off rate-limiting

### PR DESCRIPTION
**Pull request by portante**
Might want to also consider:

```
  - { var: Compress,           val: yes }
  - { var: SystemMaxUse,       val: 8G }
  - { var: SystemKeepFree,     val: 20% }
  - { var: SystemMaxFileSize,  val: 10M }
  - { var: MaxRetentionSec,    val: 1month }
  - { var: MaxFileSec,         val: 1day }
  - { var: ForwardToSyslog,    val: no }
  - { var: ForwardToWall,      val: no }
```

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@soltysh I thought we are already doing this? Wasn't there some conversation about not doing this for every environment before? I can't remember

**Comment by smarterclayton** [comment]
This alone is not sufficient for our test suites, because it doesn't cover origin-gce.  Is this a task we're going to need to do on most openshift hosts, or on those that want to get logs?

**Comment by smarterclayton** [comment]
I.e. every cluster using docker and journald has this problem, end users may need a tunable?

**Comment by portante** [comment]
@smarterclayton, why would this PR not cover origin-gce?  I don't know enough about the CI environment to understand.

Regarding users, yes, RHEL/CentOS's use of journald/rsyslog combo is hurting us.  We need to move to journald persistence, eliminating rsyslog for local log file persistence.

**Comment by smarterclayton** [comment]
origin-gce spins up a cluster on GCE using stock images.  If it's not in openshift-ansible or origin-gce (a ref arch forked playbook that wraps openshift-ansible) it doesn't get applied.

**Comment by portante** [comment]
Ah, so what do you think about changing openshift-ansible?

**Comment by smarterclayton** [comment]
Is it reasonable for us to turn off docker.service journal rate limiting in some environments?  If so, then that makes a lot of sense.

**Comment by soltysh** [comment]
> @soltysh I thought we are already doing this? Wasn't there some conversation about not doing this for every environment before? I can't remember

@stevekuznetsov this was done only in [single place](https://github.com/openshift/origin/blob/ebdb298afcc4bfbd871932a25c4030558c7a94ef/hack/test-end-to-end-docker.sh#L47-L56) because that's where we were hitting it. Although if I remember our discussions back then you were hesitant to applying this type of change globally. 

> Ah, so what do you think about changing openshift-ansible?

We've already started a discussion about it, see https://github.com/openshift/openshift-ansible/pull/3753

Personally I'm all for it 👍

**Comment by soltysh** [comment]
As for customers, we should document journald restrictions, in the short term. And move to solution proposed by @sjenning in the original issue.

**Pull request closed without merging**
