### PR TITLE
Additional debugging logging

### PR DESCRIPTION
**Pull request by jwhonce**
* Turn on more debugging logging
* Change container logging to json-file driver

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by jwhonce** [comment]
@rhvgoyal FYI

**Comment by stevekuznetsov** [comment]
So I _think_ this will be safe since `jsonfile` will make sure that we don't get rate-limited from the debug output like last time when we were using `journald`. @sdodson does this impact how the installer works at all and also @jcantrill FYI if you have `journald` tests you may need to reconfigure them if the default changes under you

**Comment by jwhonce** [comment]
@sjenning FYI

**Comment by sdodson** [comment]
@stevekuznetsov I don't think it will cause any problems, but we also don't set log driver in the latest code.

**Comment by rhvgoyal** [comment]
Thanks @jwhonce

**Comment by stevekuznetsov** [comment]
@jcantrill @richm y'all have any concerns with this?

**Comment by richm** [comment]
I just don't know what impact this will have on the logging CI.

I'm assuming we will still be able to turn on docker log-driver=journald as we do now: https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_pull_request_origin_aggregated_logging_ansible.yml#L123

I'm also assuming the extra debug information from the docker daemon debugging doesn't cause problems with our logging tests.

**Comment by stevekuznetsov** [comment]
@richm OK, if you are aware of the change and are willing to monitor your jobs for a bit I will pull this in. Any objections?

**Comment by richm** [comment]
ok - sounds good - I warned the team to be on the lookout for test flakes due to this.

**Pull request merged**
