### PR TITLE
Add Ansible 2.4 repo

### PR DESCRIPTION
**Pull request by mtnbikenc**

### CODE REVIEW

**Comment by sdodson** [comment]
LGTM, @stevekuznetsov does this get applied at AMI build time or at job time?

**Comment by mtnbikenc** [comment]
@stevekuznetsov I'm not seeing this repo in the new QE images from overnight.  Is there a base image that needs to be updated for this to take effect?

**Comment by stevekuznetsov** [comment]
This is AMI build time, we need to build and tag the AMI

**Pull request merged**
