### PR TITLE
Make jUnit callback plugin naming smarter

### PR DESCRIPTION
**Pull request by stevekuznetsov**
We only need the names of playbooks to be unique, so while the full
playbook path on disk achieves this, it also incorporates more info-
rmation than we care about. We should be fine to trim out the path
up to the `playbooks/` directories of tools we use often.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @smarterclayton this should get us succinct names and better jUnit history

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@smarterclayton any thoughts before this go in?

**Comment by smarterclayton** [comment]
Example?

**Comment by stevekuznetsov** [comment]
Takes a name like `/var/lib/jenkins/origin-ci-tool/217b2460b866b7c1af548022fcc85e0af10434c9/lib/python2.7/site-packages/oct/ansible/oct/playbooks/deprovision/main.yml` and makes instead `deprovision.main.yml`:

```xml
<?xml version="1.0" ?>
<testsuites errors="0" failures="0" tests="4" time="1.64169001579">
	<testsuite errors="0" failures="0" name="deprovision/main.yml" skipped="1" tests="4" time="1.64169001579">
		<testcase name="[localhost] ensure we have the parameters necessary to deprovision virtual hosts: ensure all required variables are set" time="0.044419">
			<skipped message="All items completed" type="skipped"/>
		</testcase>
		<testcase name="[localhost] deprovision virtual hosts in EC2: Gathering Facts" time="0.887310"/>
		<testcase name="[localhost] deprovision virtual hosts locally manged by Vagrant: Gathering Facts" time="0.397404"/>
		<testcase name="[localhost] clean up local configuration for deprovisioned instances: remove inventory configuration directory" time="0.312557"/>
	</testsuite>
</testsuites>
```

However the Jenkins interface breaks on the `.yml` so let me strip that out as well.

**Comment by stevekuznetsov** [comment]
OK, it's smarter now
```xml
<?xml version="1.0" ?>
<testsuites errors="0" failures="0" tests="4" time="1.75706720352">
	<testsuite errors="0" failures="0" name="deprovision/main" skipped="1" tests="4" time="1.75706720352">
		<testcase name="[localhost] ensure we have the parameters necessary to deprovision virtual hosts: ensure all required variables are set" time="0.039545">
			<skipped message="All items completed" type="skipped"/>
		</testcase>
		<testcase name="[localhost] deprovision virtual hosts in EC2: Gathering Facts" time="0.775894"/>
		<testcase name="[localhost] deprovision virtual hosts locally manged by Vagrant: Gathering Facts" time="0.534676"/>
		<testcase name="[localhost] clean up local configuration for deprovisioned instances: remove inventory configuration directory" time="0.406952"/>
	</testsuite>
</testsuites>
```

**Pull request merged**
