### PR TITLE
Re-add until condition on flakey ec2_ami_find

### PR DESCRIPTION
**Pull request by sdodson**
Dropped in 1ad02615c118302957694fc78c22d079a6e5e22c

### CODE REVIEW

**Comment by dobbymoodge** [comment]
Weird, I can't think of why I would have dropped that. @sdodson you've tested this change? LGTM if so

**Comment by sdodson** [comment]
> Weird, I can't think of why I would have dropped that. @sdodson you've tested this change? LGTM if so

I think it just got missed in your refactor into a block. No I have not tested this.

**Comment by stevekuznetsov** [comment]
Reverts to previous state, should be fine.

**Comment by sdodson** [comment]
Looks like the job is successful more often than not since this change.

**Pull request merged**
