### PR TITLE
get maven installed; bump to devel jdk install

### PR DESCRIPTION
**Pull request by gabemontero**
@stevekuznetsov @bparees 

i'll re-ask here:  what fills in the `?` for the jdk level ?

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
I assume it means any minor version is fine, but that is very old code -- you can try tracing it back in Vagrant if you'd like. @bparees may know

**Comment by gabemontero** [comment]
Ah - I see.  OK, I'll just spin up an instance via `oct` and see which JDK is present.  As long as it is 1.8 and not 1.7 we should be OK.  If it is 1.7, I may force it to be 1.8.

**Comment by gabemontero** [comment]
And we appear to be good:  `openjdk full version "1.8.0_131-b12"`

**Comment by bparees** [comment]
lgtm

**Comment by bparees** [comment]
@stevekuznetsov the ami build job picks up the new oct every time?  I can't remember all the moving pieces.

**Comment by gabemontero** [comment]
https://ci.openshift.redhat.com/jenkins/job/install_origin_ci_tool/61/console just ran and completed successfully

**Comment by gabemontero** [comment]
And I've initiated https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_rhel_base/165/console to update the ami.

**Comment by stevekuznetsov** [comment]
@bparees installation of `oct` onto the Jenkins master is documented [here](https://github.com/openshift/ci-config/blob/master/doc/origin-ci.md#installation-onto-the-jenkins-master) -- short of it, all jobs triggered after the global install will pick it up, as @gabemontero linked above

**Pull request merged**
