### PR TITLE
add 3.6 rhaos repos

### PR DESCRIPTION
**Pull request by gabemontero**
@stevekuznetsov

### CODE REVIEW

**Comment by bparees** [comment]
@stevekuznetsov bump

once this merges and a new ami is built, we can revert https://github.com/openshift/aos-cd-jobs/pull/374

**Comment by gabemontero** [comment]
which ami exactly needs to be built ?  none of the "classic" `base_ami` or `devenv_ami` have successfully built in a while ... are we talking (an)other ami(s) ?

**Comment by bparees** [comment]
yes, different.

**Comment by gabemontero** [comment]
Perhaps https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_rhel_base or one of its decendents?

**Comment by bparees** [comment]
yes, that one.  unfortunately the base ami for that chain is failing to build for other reasons, @stevekuznetsov is aware/working on it.

**Pull request merged**
