### PR TITLE
Added the PyLint linter

### PR DESCRIPTION
**Pull request by stevekuznetsov**
This is going to need a lot of work until it's passing. 

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
current stats:
```
      3 anomalous-backslash-in-string
      1 attribute-defined-outside-init
      1 broad-except
     45 invalid-name
      1 locally-disabled
     85 missing-docstring
     19 missing-param-doc
     24 missing-raises-doc
    128 missing-returns-doc
      1 no-self-use
     26 protected-access
      2 redefined-builtin
      1 redefined-outer-name
      1 redefined-variable-type
      1 ungrouped-imports
      3 unnecessary-lambda
      8 unused-argument
      1 using-constant-test
      8 wrong-import-order

```

**Comment by enj** [comment]
Some other static analysis tools for consideration:

1. [Prospector](https://github.com/landscapeio/prospector)
2. [Flake8](https://pypi.python.org/pypi/flake8)
3. [PySonar2](https://github.com/yinwang0/pysonar2)
4. [PyChecker](http://pychecker.sourceforge.net)

**Comment by stevekuznetsov** [comment]
Thanks @enj

**Comment by enj** [comment]
Also https://pypi.python.org/pypi/vulture

**Comment by detiber** [comment]
> Some other static analysis tools for consideration:
> - Prospector

Prospector doesn't seem to be well maintained with landscape.io not gaining traction.

> - Flake8

Flake8 is great, especially with the available plugins, it does miss a lot of correctness checks that pylint doesn't, though. It is a lot lighter weight, though.

> - PySonar2

This looks interesting, but the Java requirement is a bit odd, and would make local and Travis testing awkward.

> - PyChecker

I can't find a release for pychecker since 2011.

**Comment by detiber** [comment]
> Also https://pypi.python.org/pypi/vulture

Vulture seems promising, but it might be difficult to tune well enough to avoid false-positives for automated testing.

**Pull request closed without merging**
